[tool.poetry]
name = "flint"
version = "0.1.0"
description = "Pipeline for RACS processing, and profit along the way"
authors = ["tgalvin <tim.galvin@csiro.au>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
astropy = "^5.3.1"
numpy = "^1.25.0"
python-casacore = "^3.5.2"
scipy = "^1.11.1"
spython = "^0.3.0"

[tool.poetry.group.dev.dependencies]
black = "^23.3.0"
mypy = "^1.4.1"
isort = "^5.12.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
