[tool.poetry]
name = "flint"
version = "0.1.0"
description = "Pipeline for RACS processing, and profit along the way"
authors = ["tgalvin <tim.galvin@csiro.au>"]
license = "MIT"
readme = "README.md"
include = [
    {path = 'flint/data/model/1934-638.calibrate.txt'}
]

[tool.poetry.dependencies]
python = "^3.9"
astropy = "^5.3.1"
numpy = "^1.25.0"
python-casacore = "^3.5.2"
scipy = "^1.11.1"
spython = "^0.3.0"
fixms = "^0.1.1"
matplotlib = "*"
prefect = "^2.10.0"
prefect-dask = "^0.2.4"

[tool.poetry.group.dev.dependencies]
black = "^23.3.0"
mypy = "^1.4.1"
isort = "^5.12.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
flint_skymodel = "flint.sky_model:cli"
flint_aocalibrate = "flint.calibrate.aocalibrate:cli"
flint_flagger = "flint.flagging:cli"
flint_bandpass = "flint.bandpass:cli"
flint_ms = "flint.ms:cli"
flint_flow_bandpass = "flint.prefect.flows.calibrate:cli"
